package com.backend.Skytouch.common.enums;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    NEW_APPLICATION,
    APPLICATION_STATUS_UPDATED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_UPDATED,
    NEW_MESSAGE,
    COMPANY_APPROVED,
    COMPANY_REJECTED,
    COMPANY_SUSPENDED,
    COMPANY_ACTIVATED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_ACTIVATED,
    OFFER_EXTENDED,
    OFFER_ACCEPTED,
    OFFER_DECLINED,
    HIRED,
    JOB_ALERT_MATCH,
    JOB_ALERT_DIGEST
}