spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Skytouch_db
    username: postgres
    password: ogwaa123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  mail:
    username: ochogwuprince@gmail.com
    password: hmrxhxvcvksxapql

app:
  jwt:
    secret: mySecretKeyForJWTTokenGenerationAndValidationPurposeOnly123456789012
  auth:
    email-from: ochogwuprince@gmail.com
    log-otp: true
    mail-send-enabled: true
  frontend:
    url: http://localhost:4174

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        security: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: TRACE

    com:
      skytouch:
        config: DEBUG
        root: INFO

cloudinary:
  cloud-name: Skytouch-pdf
  api-key: 894193124153839
  api-secret: qYoUBk1aXcMY7b333tlGJL3HDDA