server:
  port: ${PORT:5000}
  forward-headers-strategy: native

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: false
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  server-url: https://skytouchjobs.up.railway.app

app:
  jwt:
    secret: ${JWT_SECRET}
  mail:
    brevo:
      api-key: ${BREVO_API_KEY}
      api-url: ${BREVO_API_URL:https://api.brevo.com/v3/smtp/email}
      sender-name: ${BREVO_SENDER_NAME:Skytouch}
  auth:
    email-from: ${APP_EMAIL_FROM:noreply@SkyTouch.com}
    log-otp: ${APP_LOG_OTP:false}
    mail-send-enabled: true
  frontend:
    url: ${APP_FRONTEND_URL}

logging:
  level:
    root: WARN
    com:
      backend:
        Skytouch: INFO