UPDATE companies
SET industry = 'OTHER' 
WHERE industry IS NOT NULL 
AND industry NOT IN (
    'TECHNOLOGY', 'FINANCE', 'HEALTHCARE', 'EDUCATION', 'RETAIL', 
    'MANUFACTURING', 'CONSTRUCTION', 'TRANSPORTATION', 'AGRICULTURE', 
    'ENERGY', 'TELECOMMUNICATIONS', 'MEDIA', 'HOSPITALITY', 'REAL_ESTATE', 
    'LEGAL', 'CONSULTING', 'GOVERNMENT', 'NON_PROFIT', 'AUTOMOTIVE', 
    'PHARMACEUTICALS', 'OTHER'
);

ALTER TABLE companies 
DROP CONSTRAINT IF EXISTS companies_industry_check;

ALTER TABLE companies 
ADD CONSTRAINT companies_industry_check 
CHECK (industry IN (
    'TECHNOLOGY', 'FINANCE', 'HEALTHCARE', 'EDUCATION', 'RETAIL', 
    'MANUFACTURING', 'CONSTRUCTION', 'TRANSPORTATION', 'AGRICULTURE', 
    'ENERGY', 'TELECOMMUNICATIONS', 'MEDIA', 'HOSPITALITY', 'REAL_ESTATE', 
    'LEGAL', 'CONSULTING', 'GOVERNMENT', 'NON_PROFIT', 'AUTOMOTIVE', 
    'PHARMACEUTICALS', 'OTHER'
) OR industry IS NULL);

-- Update job_seekers.gender to use CHECK constraint
-- First, clean up any existing invalid data
UPDATE job_seekers 
SET gender = 'PREFER_NOT_TO_SAY' 
WHERE gender IS NOT NULL 
AND gender NOT IN ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY');

ALTER TABLE job_seekers 
DROP CONSTRAINT IF EXISTS job_seekers_gender_check;

ALTER TABLE job_seekers 
ADD CONSTRAINT job_seekers_gender_check 
CHECK (gender IN ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY') OR gender IS NULL);

-- Update job_seekers.job to use CHECK constraint
-- First, clean up any existing invalid data
UPDATE job_seekers 
SET job = 'OTHER' 
WHERE job IS NOT NULL 
AND job NOT IN (
    'SOFTWARE_ENGINEER', 'DATA_SCIENTIST', 'PRODUCT_MANAGER', 'PROJECT_MANAGER', 
    'BUSINESS_ANALYST', 'MARKETING_MANAGER', 'SALES_MANAGER', 'HUMAN_RESOURCES', 
    'FINANCIAL_ANALYST', 'ACCOUNTANT', 'LAWYER', 'DOCTOR', 'NURSE', 'TEACHER', 
    'ENGINEER', 'ARCHITECT', 'DESIGNER', 'WRITER', 'CONSULTANT', 'EXECUTIVE', 
    'ADMINISTRATIVE', 'CUSTOMER_SERVICE', 'OPERATIONS_MANAGER', 'RESEARCHER', 
    'ANALYST', 'DEVELOPER', 'MANAGER', 'DIRECTOR', 'SPECIALIST', 'COORDINATOR', 
    'ASSISTANT', 'OTHER'
);

ALTER TABLE job_seekers 
DROP CONSTRAINT IF EXISTS job_seekers_job_check;

ALTER TABLE job_seekers 
ADD CONSTRAINT job_seekers_job_check 
CHECK (job IN (
    'SOFTWARE_ENGINEER', 'DATA_SCIENTIST', 'PRODUCT_MANAGER', 'PROJECT_MANAGER', 
    'BUSINESS_ANALYST', 'MARKETING_MANAGER', 'SALES_MANAGER', 'HUMAN_RESOURCES', 
    'FINANCIAL_ANALYST', 'ACCOUNTANT', 'LAWYER', 'DOCTOR', 'NURSE', 'TEACHER', 
    'ENGINEER', 'ARCHITECT', 'DESIGNER', 'WRITER', 'CONSULTANT', 'EXECUTIVE', 
    'ADMINISTRATIVE', 'CUSTOMER_SERVICE', 'OPERATIONS_MANAGER', 'RESEARCHER', 
    'ANALYST', 'DEVELOPER', 'MANAGER', 'DIRECTOR', 'SPECIALIST', 'COORDINATOR', 
    'ASSISTANT', 'OTHER'
) OR job IS NULL);

-- Update job_seekers.qualification to use CHECK constraint
-- First, clean up any existing invalid data
UPDATE job_seekers 
SET qualification = 'OTHER' 
WHERE qualification IS NOT NULL 
AND qualification NOT IN (
    'HIGH_SCHOOL', 'DIPLOMA', 'BACHELOR_DEGREE', 'MASTER_DEGREE', 
    'DOCTORATE', 'PROFESSIONAL_CERTIFICATION', 'VOCATIONAL_TRAINING', 'OTHER'
);

ALTER TABLE job_seekers 
DROP CONSTRAINT IF EXISTS job_seekers_qualification_check;

ALTER TABLE job_seekers 
ADD CONSTRAINT job_seekers_qualification_check 
CHECK (qualification IN (
    'HIGH_SCHOOL', 'DIPLOMA', 'BACHELOR_DEGREE', 'MASTER_DEGREE', 
    'DOCTORATE', 'PROFESSIONAL_CERTIFICATION', 'VOCATIONAL_TRAINING', 'OTHER'
) OR qualification IS NULL);

-- Update job_alerts.industry to use CHECK constraint (for consistency)
-- First, clean up any existing invalid data
UPDATE job_alerts 
SET industry = 'OTHER' 
WHERE industry IS NOT NULL 
AND industry NOT IN (
    'TECHNOLOGY', 'FINANCE', 'HEALTHCARE', 'EDUCATION', 'RETAIL', 
    'MANUFACTURING', 'CONSTRUCTION', 'TRANSPORTATION', 'AGRICULTURE', 
    'ENERGY', 'TELECOMMUNICATIONS', 'MEDIA', 'HOSPITALITY', 'REAL_ESTATE', 
    'LEGAL', 'CONSULTING', 'GOVERNMENT', 'NON_PROFIT', 'AUTOMOTIVE', 
    'PHARMACEUTICALS', 'OTHER'
);

ALTER TABLE job_alerts 
DROP CONSTRAINT IF EXISTS job_alerts_industry_check;

ALTER TABLE job_alerts 
ADD CONSTRAINT job_alerts_industry_check 
CHECK (industry IN (
    'TECHNOLOGY', 'FINANCE', 'HEALTHCARE', 'EDUCATION', 'RETAIL', 
    'MANUFACTURING', 'CONSTRUCTION', 'TRANSPORTATION', 'AGRICULTURE', 
    'ENERGY', 'TELECOMMUNICATIONS', 'MEDIA', 'HOSPITALITY', 'REAL_ESTATE', 
    'LEGAL', 'CONSULTING', 'GOVERNMENT', 'NON_PROFIT', 'AUTOMOTIVE', 
    'PHARMACEUTICALS', 'OTHER'
) OR industry IS NULL);
