CREATE TABLE job_seekers (
    id              UUID         NOT NULL PRIMARY KEY,
    user_username   VARCHAR(255) NOT NULL UNIQUE REFERENCES users (email),
    status          VARCHAR(50)  NOT NULL,
    first_name      VARCHAR(255),
    middle_name     VARCHAR(255),
    last_name       VARCHAR(255),
    phone           VARCHAR(50),
    gender          VARCHAR(50),
    birthday        DATE,
    religion        VARCHAR(100),
    nin             VARCHAR(50),
    job             VARCHAR(255),
    qualification   VARCHAR(255),
    cv              TEXT,
    about           TEXT,
    open_to_work    BOOLEAN      NOT NULL DEFAULT FALSE,
    payment_status  VARCHAR(50),
    address_no      VARCHAR(100),
    address_line    VARCHAR(255),
    address_lga     VARCHAR(100),
    address_state   VARCHAR(100),
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP
);
